[package]
name = "r4l"
version = "0.1.0"
edition = "2021"
authors = ["Guoweikang <guoweikang.kernel@gmail.com>"]
description = "OS interface abstract layer for r4l"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = ""
repository = "https://github.com/guoweikang/r4l.git"

[features]
rust_os=[]
arceos=["rust_os", "axerrno", "axtask/irq", "axlog", "axhal", "axsync", "linked_list"]

[dependencies]
bitflags = "2.5.0"
derive_builder = {version ="0.20", default-features = false}
cfg-if = "1.0"

macros = {package ="r4l-macros", path = "../macros"}
of_fdt = {package ="of_fdt", path = "../of"}

# Arceos Starry dependencies
axtask = { workspace = true, optional = true }
axlog = { workspace = true, optional = true  }
axhal = { workspace = true, optional = true }
axsync = { workspace = true, optional = true }
axerrno = {git = "https://github.com/Starry-OS/axerrno.git", optional=true}
linked_list = {git = "https://github.com/Starry-OS/linked_list.git", optional=true}
